### ISSUE TITLE
Simplify launching of executable in Linux

### ISSUE THREAD

**Issue by Poorchop** [turtl/js#158]
I didn't realize that the desktop application used node-webkit until I tried using it in Linux, but as you might already be aware, there is a known issue regarding libudev.so.0 when trying to launch nw executables in Linux. I opened an [issue](https://github.com/bastimeyer/livestreamer-twitch-gui/issues/2) for the same problem that I had with another application, and the developer wrote a [script](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/master/build/resources/linux/start.sh) that automatically creates the necessary symlink. I thought that maybe you would want to do the same for turtl since it would eliminate that extra step and help keep from scaring new users away.

**Comment by orthecreedence** [comment]
This is a great idea, and I am a fool for not doing this sooner. I'll try to get a fix for this pushed out tonight or tomorrow for Turtl's wonderful linux users. I'm going to close this issue since I'll be putting this on the Turtl trello list ([our new todo list](http://turtlapp.tumblr.com/post/117912136817/moving-feature-tracker-off-github))

**Comment by orthecreedence** [comment]
Just a heads up, this was fixed tonight. Would love if you could download the latest [Linux release](https://turtl.it/download) and let me know if it starts for you. Thanks!

**Comment by Poorchop** [comment]
I think you're using `slocate`, but there isn't even a package for that in my repos (Fedora 21). I've always just used `mlocate`.

It actually looks like it creates the symlink the first time, but turtl still doesn't launch. 

First attempt:
```
./turtl: line 7: slocate: command not found
./turtl: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```

Second attempt:
```
./turtl: line 7: slocate: command not found
ln: failed to create symbolic link ‘./libudev.so.0’: File exists
./turtl: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```

**Comment by orthecreedence** [comment]
Thank you for testing! I copied the script you linked (somehow missed that the first time) and republished.

**Comment by Poorchop** [comment]
Yup it's working now. Not sure if it's the same exact implementation because I don't see the symlinked library in the livestreamer-twitch-gui folder after launching that application, but I can actually see it in the turtl folder. In any case, it works. Thanks for pushing this so quickly.

**Comment by orthecreedence** [comment]
Glad it's working =]. Thank you for testing.
